### ISSUE TITLE
Word Highlight while Searching

### ISSUE THREAD

**Issue by Williams-Ren** [16soundsofsilence/typora-gitbook-theme#11]
![image](https://user-images.githubusercontent.com/45218090/106754382-c3165600-65e1-11eb-87d4-bbdd331b26ed.png)

As you may see in the picture. When I'm searching for some words that is highlighted by ==word== syntax was changed in to the same color as the background. Maybe change it to another color would be better?

**Comment by 16soundsofsilence** [comment]
Hello,
thanks for your feedback. A fix is being worked on. Expect an update addressing this issue soon.

**Comment by 16soundsofsilence** [comment]
Version 1.9 uses a gray color to mark search hits, so they are now properly distinguishable.
