### ISSUE TITLE
Readability of Links in Highlighted Mode

### ISSUE THREAD

**Issue by Williams-Ren** [16soundsofsilence/typora-gitbook-theme#12]
![Snipaste_2021-02-15_18-08-38](https://user-images.githubusercontent.com/45218090/107933191-63448580-6fb9-11eb-9ef6-ab3e8dc5f052.png)
![Snipaste_2021-02-15_18-08-44](https://user-images.githubusercontent.com/45218090/107933198-650e4900-6fb9-11eb-871d-e6ca6c9e12ba.png)
![Snipaste_2021-02-15_18-09-37](https://user-images.githubusercontent.com/45218090/107933202-65a6df80-6fb9-11eb-8277-82b3e6e406fa.png)

Similar issue with the last one I posted. The font color is exactly the same as highlighted background when editing. Merely visible when I put my cursor on the link. Could you change the font color a bit to increase the readability?

Thank you sooooo much for making this theme! It is now my favorite theme!

**Comment by 16soundsofsilence** [comment]
The issue has been resolved in the [latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/tag/v1.9.1).
I appreciate it a lot that you like this theme!
