### ISSUE TITLE
Minor Display Issue When Selecting Texts

### ISSUE THREAD

**Issue by Williams-Ren** [16soundsofsilence/typora-gitbook-theme#13]
![image](https://user-images.githubusercontent.com/45218090/108627663-c179d880-7491-11eb-8475-b0bc0851476d.png)

Hi! As I circled out in the picture that when selecting a part of text containning highlighted text, the background of beginning of each line and the end of each line is not properly hightlighted.

**Comment by 16soundsofsilence** [comment]
Hi @Williams-Ren,
unfortunately the options for styling selected text in CSS are extremely limited (to be exact it is only possible to modify the background color, text color and the text shadow). Most of its attributes are determined by the browser engine (for Typora that is Chromium on Windows and Linux and WebKit on macOS).

Chromium seems to handle padding (which I am using around the highlighted text) sitting within selected text a little bit different than WebKit. On macOS it is looking like it should:
<img width="837" alt="Screenshot 2021-02-22 um 17 32 10" src="https://user-images.githubusercontent.com/48356881/108738571-0bb39600-7534-11eb-895a-a3ea09f3ea16.png">

I will have a look into this in the following days and try to figure out a workaround. However, I am not sure if there is one 😕

**Comment by 16soundsofsilence** [comment]
Hey,
sadly I couldn't come up with a solution. If I am able to do so in the future, I will get back to this issue.
