### ISSUE TITLE
Background Color for Gitbook Slate

### ISSUE THREAD

**Issue by chchen-stanford** [16soundsofsilence/typora-gitbook-theme#14]
Gitbook Azure/Slate are my primary Typora themes. Thanks for sharing these beautiful themes!

Right now I am still using v1.8 because I like the bluish background better. The new background in v1.9.1 is a little too dark for me. I wonder if you could code the CSS in a way that is very easy to tweak the background color, perhaps by changing one or two global variables under :root?

**Comment by 16soundsofsilence** [comment]
Hello @chchen-stanford,
I think I've found a solution that would make this relatively easy for everyone. I'd outsource the colors of the slate variant into a separate CSS file within the gitbook folder. But I would also put another CSS file containing the old colors in the folder. All you would have to do then, is to change the import statement at the very top of the file from `@import "gitbook/slate-colors.css";` to `@import "gitbook/old-slate-colors.css";`. If you are ok with this solution, I'd update the theme in that way in the next 1 or 2 days or so.

**Comment by chchen-stanford** [comment]
@16soundsofsilence, this sounds like a great solution. Thanks for addressing my comment so promptly!

**Comment by 16soundsofsilence** [comment]
The discussed solution has been implemented in the [latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/tag/v1.9.2). Thank you for your feedback.

**Comment by chchen-stanford** [comment]
This solution works great. Note that `@import "gitbook/old-slate-colors.css";` can also be incorporated into a separate gitbook-slate.user.css, saved along with gitbook-slate.css. This way, there is no change to the original theme, making it easier for future updates.

**Comment by 16soundsofsilence** [comment]
Oh, I didn't think of that. That makes it even easier to use... :)
