### ISSUE TITLE
slate显示为白色

### ISSUE THREAD

**Issue by yushengjiaohuang** [16soundsofsilence/typora-gitbook-theme#17]
![image](https://user-images.githubusercontent.com/43739253/117473254-561dae00-af8c-11eb-93ac-235d6ac78c67.png)
slate不是暗黑模式吗？我的背景显示为白色

**Comment by 16soundsofsilence** [comment]
Hello @yushengjiaohuang,
did you put the folder `gitbook`, which is inside of the downloaded zip file, into the themes folder?
It contains important things like fonts and css files specifying colors.

**Comment by yushengjiaohuang** [comment]
OK, it's been solved. It's really the reason for the lack of documents. Thank you. Nice theme.
