### ISSUE TITLE
Shake problem.

### ISSUE THREAD

**Issue by HYBB-rash** [16soundsofsilence/typora-gitbook-theme#19]
I commit an issue in Typora, [click here to jump](https://github.com/typora/typora-issues/issues/4429) , finally I find that the problem only happen in Gitbook theme.

**Comment by 16soundsofsilence** [comment]
Hi @HYBB-rash,
your issue has been addressed [in the latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/tag/v1.10.1). As you might have noticed, I explained the cause of the problem on the issue of the Typora repository.

The stuttering shouldn't occur anymore, at least it doesn't for me.
 
However, I couldn't reproduce the issue, where you have to click twice on the outline items.

Can you give me some feedback on whether these issues are resolved for you now?

**Comment by HYBB-rash** [comment]
@16soundsofsilence 

Thanks! The latest release is work well for me! The stuttering problem have been resolve! Thank for you reply rapidly!
