### ISSUE TITLE
small detail when writing the language

### ISSUE THREAD

**Issue by ghost** [16soundsofsilence/typora-gitbook-theme#3]
**Congratulations on creating this theme, I really love it.**
I just found a minute detail
![issues](https://user-images.githubusercontent.com/64546948/96938984-23094680-14a2-11eb-8f9b-3806b8ddd45c.png)

> macOS Catalina 10.15.7 
> Typora 0.9.9.35.2

**Comment by Williams-Ren** [comment]
Have similar issue when trying write a Mermaid graph by using following syntax:

```Mermaid
graph TD

A-->B

some other code
```

It seems that line numer sometimes doesn't show up and the code with covered by the part where originally should be the line number

**Comment by 16soundsofsilence** [comment]
Hello, thanks for your feedback. I noticed the second problem too. Weirdly, the layout "fixes itself" once you add 10 or more lines. Now you can even delete these lines again and the lines will stay in place. Also if you switch to a different theme and then back to this one, the isssue disappears - at least on my computer. To me it seems like this is some kind of Code Mirror or Typora issue. Similar issues can be observed in other themes as well, e.g. Cobalt.

Sadly, I haven't found a way to solve these issues with css yet - the behaviour of these Code Mirror boxes is very inconsistent. But I will continue trying to solve them...
