### ISSUE TITLE
Rounded Cornor of Highlighted Part

### ISSUE THREAD

**Issue by Williams-Ren** [16soundsofsilence/typora-gitbook-theme#8]
Thank you for the theme!!! I really love it, but I found there are some details are not very good.

As you may see in the picture below, the cornor of highlight is only rounded at the begining and at the end. And when it come to a new line, it is 90 degree sharp, which I think is not very consistant with the design.
Could you make an improvment on it?

![image](https://user-images.githubusercontent.com/45218090/104116975-6fa14700-5358-11eb-910e-55c5f7981541.png)

**Comment by Williams-Ren** [comment]
Forgot to add. I'm running it on Win 10.

**Comment by 16soundsofsilence** [comment]
Hello, thanks for your feedback. I am currently working on a fix.

**Comment by 16soundsofsilence** [comment]
This issue was fixed in the [latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/tag/v1.6.1).

**Comment by 16soundsofsilence** [comment]
On my PC it looks like this:
![image](https://user-images.githubusercontent.com/48356881/104305646-3b02cc00-54cd-11eb-8443-81dd1143545c.png)

**Comment by 16soundsofsilence** [comment]
Just to make sure we both use the same version of the file. Could you open one of the css files and search for this line?
`box-decoration-break: clone;` Should be line 324 in the `gitbook-teal.css` file.

**Comment by 16soundsofsilence** [comment]
So I think I figured out what might be the problem. Looking at the screenshot of file explorer you have posted in #9, I'm assuming you put the extracted folder `gitbook-v1-6-1` into the themes folder. However, the contents of this folder, which are the `gitbook` folder and the three css files, need to be placed directly into the themes folder replacing the gitbook files of older versions to be able to be accessed by Typora.
