### ISSUE TITLE
Minor Display Issue of Math Block

### ISSUE THREAD

**Issue by Williams-Ren** [16soundsofsilence/typora-gitbook-theme#9]
Running on Win 10.

When using a BIG symboy like \sum, the lower part will go out from the box when having preview. No problem found in final view. Don't know whether it is Typora's problem.

![Snipaste_2021-01-11_22-57-10](https://user-images.githubusercontent.com/45218090/104274541-09ddc800-54dc-11eb-9dbc-581a78dd710d.png)

BTW, I haven't fix the problem #8 by the 1.6.1 release. I paste the unzipped zip folder to the theme folder, but the connor is still sharp as it was.

![image](https://user-images.githubusercontent.com/45218090/104274842-b15afa80-54dc-11eb-8f01-b42b6949caae.png)

![image](https://user-images.githubusercontent.com/45218090/104274892-ce8fc900-54dc-11eb-8548-5ccfef08b709.png)

**Comment by 16soundsofsilence** [comment]
Hello, I didn't really like the way these math-boxes look anyways, so I'll redo them pretty soon.

**Comment by 16soundsofsilence** [comment]
Update: I have changed the math blocks in the  [latest release](https://github.com/16soundsofsilence/typora-gitbook-theme/releases/tag/v1.7), as announced. This should fix the problem:

<img width="849" alt="Bildschirmfoto 2021-01-14 um 19 49 57" src="https://user-images.githubusercontent.com/48356881/104635055-b4531800-56a1-11eb-89b6-e1162347c5c2.png">
